[package]
name = "rBF"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorful = "0.2.2"
getch = "0.3.1"
hlua = "0.4.1"
once_cell = "1.18.0"